### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by jayjay958** [john01dav/SQLPermsIssues#17]
- Support Vault 

- Please fix essentials permissions (your plugin give all essentials permission by default)

- Remove OP: true and add - '*' like PEX instead it should be useful Also Can be use like this
permissions:
  - -testperm.*

100 Star for these thing
Thanks!

Sorry my bad English

**Comment by john01dav** [comment]
Vault support isn't likely any time soon because Vault's API doesn't clearly match to how SQLPerms works. 

The only way a player will get permissions by default is if a plugin says it is to be so. If you do not want to allow a player to have a permission, negate it by prefixing it with a '-', for instance, a list entry to remove essentials.warp would be "- -essentials.warp"

The '*' permission node would require a hacky method which could easily break compatibility with other plugins. testperm.* like permissions need to be implemented by the plugin that owns the child permissions.

**Comment by john01dav** [comment]
Closed due to inactivity, feel free to re-open it if you come back.
