### ISSUE TITLE
Star Perms * & op

### ISSUE THREAD

**Issue by DynamicMC** [john01dav/SQLPermsIssues#24]
When I give myself star perms by itself, (- '*') or for a specific plugin (- essentials.*) I don't recieve the permissions. Also when I'm op I don't get the permissions either.

**Comment by john01dav** [comment]
Star permissions aren't supported in SQLPerms. Please verify that you are actually operator (ie. that the bug is that operator isn't working rather than you not being an operator) before checking if the permissions don't work. Also, /op won't work with SQLPerms -- instead, you need to setup who is and isn't an operator in permissions.yml and with /setrank.

**Comment by DynamicMC** [comment]
I'm opped. Its just I don't recieve the permissions I normally would if I was op.

**Comment by DynamicMC** [comment]
actually, its the OP perms not updating when I switch a rank.

**Comment by DynamicMC** [comment]
Also, theres no permission node for gplayerperms?

**Comment by john01dav** [comment]
Please include detailed steps to reproduce the issue regarding the non-updating of operator permissions.

>Also, theres no permission node for gplayerperms?
sqlperms.playerperms.global, defaults to op

**Comment by john01dav** [comment]
Double Issue, Please create one issue per actual issue.
